#! /usr/bin/perl -w
use strict;
use warnings;
use CGI;

my $safe_filename_characters = "a-zA-Z0-9_.-";
my $upload_dir = "/opt/muzyka";

my $query = new CGI;
my $file = $query->param("file");
my $safefile = $file;

sub htmltextout
{
	my $text = $_[0];
	print $query->header(
		-type => "text/html",
		-charset => "utf-8");
	print "<html>\n<body>\n<p>$text</p>\n</body>\n</html>";
}

$safefile =~ tr/ /_/;
$safefile =~ s/[^$safe_filename_characters]//g;
if ("$safefile" != "$file")
{
	htmltextout("Dziwne znaki w nazwie pliku");
	exit;
}

my $fullfile = "$upload_dir/$safefile";
system("/usr/bin/sudo -u uv /usr/bin/play $fullfile &");

htmltextout("Rzucono zaklęcie $safefile");

